name: Build Reader

on: 
  pull_request:
    branches:
      - reader
      - reader_class_tests

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: izmkirill/pastebin_actions:latest
        credentials:
            username: izmkirill
            password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    steps:      
      - name: Build
        run: |
          cd /usr/src/app/src/reader
          cmake . -B build
          cd build
          make -j4
      - name: End
        if: success() || failure()
        run: |
          exit
          ./down.sh