name: Build Reader

on: 
  pull_request:
    branches:
      - reader

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: izmkirill/pastebin_enviroment:latest
        credentials:
            username: izmkirill
            password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    steps:  
      - name: Clone project
        uses: actions/checkout@v4    
      - name: Build
        run: |
          cd src/reader/scripts 
          ./build.sh
      - name: End
        if: success() || failure()
        run: |
          exit
          ./down.sh