name: Unit Tests Reader

on: 
  pull_request:
    branches:
      - reader

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
        image: izmkirill/pastebin_enviroment:latest
        credentials:
            username: izmkirill
            password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    steps:   
      - name: Clone project
        uses: actions/checkout@v4   
      - name: Build
        run: |
          cd src/reader/scripts 
          ./build.sh
      - name: Test Reader implementation
        run: |
          cd src/reader/scripts 
          ./test.sh reader ut
      - name: Test gRPC Reader implementation
        run: |
          cd src/reader/scripts 
          ./test.sh server ut
      - name: End
        if: success() || failure()
        run: |
          exit
          ./down.sh